version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sensoteq-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    volumes:
      - ./db/dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar

  api:
    build: .
    container_name: sensoteq-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/dvdrental
