version: "3.9"
services:
  db:
    image: sensoteq/tech-assessment-db:latest
    container_name: sensoteq-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dvdrental
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dvdrental"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    build: .
    container_name: sensoteq-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/dvdrental
      NODE_ENV: development
    ports:
      - "3000:3000"
