name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: |
            backend/pnpm-lock.yaml
            frontend/pnpm-lock.yaml

      - name: Install pnpm
        run: npm install -g pnpm@9

      # ---------- Backend ----------
      - name: Backend install
        run: pnpm install --frozen-lockfile
        working-directory: backend

      - name: Backend build
        run: pnpm run build
        working-directory: backend

      - name: Backend test
        run: pnpm test -- --run
        working-directory: backend

      # ---------- Frontend ----------
      - name: Frontend install
        run: pnpm install --frozen-lockfile
        working-directory: frontend

      - name: Frontend build
        run: pnpm run build
        working-directory: frontend
        env:
          # optional; your code already has a fallback, but set it if you want
          VITE_API_BASE: http://localhost:3000
